name: Run Tests and Check Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    # Upgrade pip, setuptools, and wheel to avoid issues during package installs
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Install dependencies and handle encoding issue on Windows
    - name: Install dependencies
      env:
        PYTHONIOENCODING: utf-8  # Ensure Python uses UTF-8 encoding
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          chcp 65001 | python -m pip install -e .[test]
        else
          python -m pip install -e .[test]
        fi
    
    - name: Code formatting
      run: |
        pip install "black[jupyter]==24.4.2"
        black --check .

    - name: Test with pytest
      run: |
        pytest --color=yes
